//
//  File.swift
//  KernelSwiftUtilities
//
//  Created by Jonathan Forbes on 29/08/2024.
//

import KernelSwiftCommon
import Vapor
import Fluent

extension KernelCurrency.Core.ISO4217 {
    public enum HistoricCurrencyCode: String, FluentStringEnum {
        public static let fluentEnumName: String = "ksc-iso_4217_historic_currency_code"
        
        case ADP = "ADP"
        case AFA = "AFA"
        case ALK = "ALK"
        case AOK = "AOK"
        case AON = "AON"
        case AOR = "AOR"
        case ARA = "ARA"
        case ARP = "ARP"
        case ARY = "ARY"
        case ATS = "ATS"
        case AYM = "AYM"
        case AZM = "AZM"
        case BAD = "BAD"
        case BEC = "BEC"
        case BEF = "BEF"
        case BEL = "BEL"
        case BGJ = "BGJ"
        case BGK = "BGK"
        case BGL = "BGL"
        case BOP = "BOP"
        case BRB = "BRB"
        case BRC = "BRC"
        case BRE = "BRE"
        case BRN = "BRN"
        case BRR = "BRR"
        case BUK = "BUK"
        case BYB = "BYB"
        case BYR = "BYR"
        case CHC = "CHC"
        case CSD = "CSD"
        case CSJ = "CSJ"
        case CSK = "CSK"
        case CYP = "CYP"
        case DDM = "DDM"
        case DEM = "DEM"
        case ECS = "ECS"
        case ECV = "ECV"
        case EEK = "EEK"
        case ESA = "ESA"
        case ESB = "ESB"
        case ESP = "ESP"
        case FIM = "FIM"
        case FRF = "FRF"
        case GEK = "GEK"
        case GHC = "GHC"
        case GHP = "GHP"
        case GNE = "GNE"
        case GNS = "GNS"
        case GQE = "GQE"
        case GRD = "GRD"
        case GWE = "GWE"
        case GWP = "GWP"
        case HRD = "HRD"
        case IEP = "IEP"
        case ILP = "ILP"
        case ILR = "ILR"
        case ISJ = "ISJ"
        case ITL = "ITL"
        case LAJ = "LAJ"
        case LSM = "LSM"
        case LTL = "LTL"
        case LTT = "LTT"
        case LUC = "LUC"
        case LUF = "LUF"
        case LUL = "LUL"
        case LVL = "LVL"
        case LVR = "LVR"
        case MGF = "MGF"
        case MLF = "MLF"
        case MRO = "MRO"
        case MTL = "MTL"
        case MTP = "MTP"
        case MVQ = "MVQ"
        case MXP = "MXP"
        case MZE = "MZE"
        case MZM = "MZM"
        case NIC = "NIC"
        case NLG = "NLG"
        case PEH = "PEH"
        case PEI = "PEI"
        case PES = "PES"
        case PLZ = "PLZ"
        case PTE = "PTE"
        case RHD = "RHD"
        case ROK = "ROK"
        case ROL = "ROL"
        case RUR = "RUR"
        case SDD = "SDD"
        case SDP = "SDP"
        case SIT = "SIT"
        case SKK = "SKK"
        case SRG = "SRG"
        case STD = "STD"
        case SUR = "SUR"
        case TJR = "TJR"
        case TMM = "TMM"
        case TPE = "TPE"
        case TRL = "TRL"
        case UAK = "UAK"
        case UGS = "UGS"
        case UGW = "UGW"
        case USS = "USS"
        case UYN = "UYN"
        case UYP = "UYP"
        case VEB = "VEB"
        case VEF = "VEF"
        case VNC = "VNC"
        case XEU = "XEU"
        case XFO = "XFO"
        case XFU = "XFU"
        case XRE = "XRE"
        case YDD = "YDD"
        case YUD = "YUD"
        case YUM = "YUM"
        case YUN = "YUN"
        case ZAL = "ZAL"
        case ZMK = "ZMK"
        case ZRN = "ZRN"
        case ZRZ = "ZRZ"
        case ZWC = "ZWC"
        case ZWD = "ZWD"
        case ZWN = "ZWN"
        case ZWR = "ZWR"
        case unknown = ""
    }
}
