# ================================
# Build image
# ================================
FROM swift:5.9.1-jammy as build-ksu-crypto-x509

# Install OS updates
RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
    && apt-get -q update \
    && apt-get -q dist-upgrade -y\
    && rm -rf /var/lib/apt/lists/*

# Set up a build area
WORKDIR /build-ksu-crypto-x509

# First just resolve dependencies.
# This creates a cached layer that can be reused
# as long as your Package.swift/Package.resolved
# files do not change.
COPY ./Package.* ./
COPY ./KSU.xcworkspace/xcshareddata/swiftpm/Package.* ./
RUN swift package resolve --skip-update \
        "$([ -f ./Package.resolved ] && echo "--force-resolved-versions" || true)"

# Copy entire repo into container
COPY ./Keys ./Keys
COPY ./Sources ./Sources
COPY ./Tests ./Tests

# Build everything, with optimizations
RUN swift build -c release --product KSUCryptoX509DemoServer --static-swift-stdlib
    # -Xlinker -u -Xlinker _swift_backtrace_isThunkFunction
    # Workaround for https://github.com/apple/swift/pull/68669
    # This can be removed as soon as 5.9.1 is released, but is harmless if left in.

# Switch to the staging area
WORKDIR /staging-ksu-crypto-x509

# Copy main executable to staging area
RUN cp "$(swift build --package-path /build-ksu-crypto-x509 -c release --show-bin-path)/KSUCryptoX509DemoServer" ./

# Copy resources bundled by SPM to staging area
RUN find -L "$(swift build --package-path /build-ksu-crypto-x509 -c release --show-bin-path)/" -regex '.*\.resources$' -exec cp -Ra {} ./ \;

# Copy any resources from the public directory and views directory if the directories exist
# Ensure that by default, neither the directory nor any of its contents are writable.
RUN [ -d /build-ksu-crypto-x509/Public ] && { mv /build-ksu-crypto-x509/Public ./Public && chmod -R a-w ./Public; } || true
RUN [ -d /build-ksu-crypto-x509/Resources ] && { mv /build-ksu-crypto-x509/Resources ./Resources && chmod -R a-w ./Resources; } || true
RUN [ -d /build-ksu-crypto-x509/Keys ] && { mv /build-ksu-crypto-x509/Keys ./Keys; } || true

# ================================
# Run image
# ================================
FROM swift:5.9.1-jammy-slim

# Make sure all system packages are up to date, and install only essential packages.
RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
    && apt-get -q update \
    && apt-get -q dist-upgrade -y \
    && apt-get -q install -y \
      ca-certificates \
      tzdata \
# If your app or its dependencies import FoundationNetworking, also install `libcurl4`.
      # libcurl4 \
# If your app or its dependencies import FoundationXML, also install `libxml2`.
      # libxml2 \
    && rm -r /var/lib/apt/lists/*

# Create a vapor user and group with /app as its home directory
RUN useradd --user-group --create-home --system --skel /dev/null --home-dir /KSUCryptoX509DemoServer vapor

# Switch to the new home directory
WORKDIR /KSUCryptoX509DemoServer

# Copy built executable and any staged resources from builder
COPY --from=build-ksu-crypto-x509 --chown=vapor:vapor /staging-ksu-crypto-x509 /KSUCryptoX509DemoServer

# Provide configuration needed by the built-in crash reporter and some sensible default behaviors.
ENV SWIFT_ROOT=/usr SWIFT_BACKTRACE=enable=yes,sanitize=yes,threads=all,images=all,interactive=no

# Ensure all further commands run as the vapor user
USER vapor:vapor

# Let Docker bind to port 8080
EXPOSE 8080

# Start the Vapor service when the image is run, default to listening on 8080 in production environment
ENTRYPOINT ["./KSUCryptoX509DemoServer"]

CMD ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

