//
//  File.swift
//
//
//  Created by Jonathan Forbes on 03/10/2023.
//

import Vapor
import Fluent
import Dispatch
import Logging
import KernelSwiftServer
import KernelSwiftCommon
import NIOSSL

private extension Application {
    static let baseExecutionQueue = DispatchQueue(label: "kerneledge.ksu.crypto-x509.demo-server")
    
    func runFromAsyncMainEntrypoint() async throws {
        try await withCheckedThrowingContinuation { continuation in
            Application.baseExecutionQueue.async { [self] in
                do {
                    try self.run()
                    continuation.resume()
                } catch {
                    continuation.resume(throwing: error)
                }
            }
        }
    }
}

@main
enum Entrypoint {
    static func main() async throws {
        var env = try Environment.detect()
        #if canImport(Darwin)
        let logLevel = try Logger.Level.detect(from: &env)
        KernelSwiftCommon.bootstrapLogging("KSU", logLevel: logLevel)
        #else
        try LoggingSystem.bootstrap(from: &env)
        #endif
        let app = Application.initDI(env)
        do {
            try await configureApp(app)
        } catch {
            app.logger.report(error: error)
            try? await app.asyncShutdown()
            throw error
        }
        try await app.execute()
        try await app.asyncShutdown()
    }
}

public func configureApp(_ app: Application, _ portOverride: Int? = nil) async throws {
    let port = portOverride ?? Environment.get("HTTP_PORT").flatMap(Int.init(_:)) ?? 8080
    app.http.server.configuration.port = port
    app.http.server.configuration.supportVersions = Set<HTTPVersionMajor>([.two])
    app.http.server.configuration.supportPipelining = true

    let serverRootCertificatePath = "Keys/DemoSSL/minica.pem"
    let serverCertificatePath = "Keys/DemoSSL/cert.pem"
    let serverPrivateKeyPath = "Keys/DemoSSL/key.pem"
    let dbRootCertificatePath = "Keys/DemoSSL/myCA.crt"
    let dbCertificatePath = "Keys/DemoSSL/postgresdb.crt"
    let dbPrivateKeyPath = "Keys/DemoSSL/postgresdb.key"
    var serverSSLConf: TLSConfiguration = try .makeServerConfiguration(
        certificateChain: [
            NIOSSLCertificateSource.certificate(NIOSSLCertificate(file: serverCertificatePath, format: .pem)),
            NIOSSLCertificateSource.certificate(NIOSSLCertificate(file: serverRootCertificatePath, format: .pem))
        ],
        privateKey: .privateKey(.init(file: serverPrivateKeyPath, format: .pem))
    )
    
    // becuase there is no trusted system root CA?
    serverSSLConf.certificateVerification = .none
    app.http.server.configuration.tlsConfiguration = serverSSLConf
    
    // these seem to slide down the turnk to the root
    var dbSSLConf: TLSConfiguration = .makeClientConfiguration()
    try dbSSLConf.certificateChain = .init([
        .certificate(.init(file: dbCertificatePath, format: .pem)),
        .certificate(.init(file: dbRootCertificatePath, format: .pem))
    ])
    
    // private key generated by client before csr to CA-1?
    try dbSSLConf.privateKey = .privateKey(.init(file: dbPrivateKeyPath, format: .pem))
    // becuase there is no trusted system root CA?
    // or no dns?
    dbSSLConf.certificateVerification = .none
    let dbTimeout = 3
    app.logger.debug("using DB SSL config: \(dbSSLConf)")
    app.logger.notice("DB Initialisation Timeout (\(dbTimeout) \(dbTimeout == 1 ? "second" : "seconds"))")
    try await Task.sleep(for: .seconds(dbTimeout))

    app.databases.use(
        .postgres(
            configuration: .init(
                hostname: Environment.get("DATABASE_HOST") ?? "127.0.0.1",
                port: Environment.get("DATABASE_PORT").flatMap(Int.init(_:)) ?? 5432,
                username: "postgresdb",
                password: "postgresdb",
                database: "ksu_crypto_x509",
                tls: .require(try .init(configuration: dbSSLConf))
                //tls: .disable
            ),
            maxConnectionsPerEventLoop: 5,
            connectionPoolTimeout: .seconds(60),
            sqlLogLevel: .debug
        ),
        as: .psql
    )
    
    KernelServerPlatform.initialise()
    try await KernelNetworking.initialise()
    try await KernelTaskScheduler.initialise()
    try await KernelX509.initialise(
        withConfiguration: [
            (.defaultDatabaseID, DatabaseID.psql)
        ]
    )
    
    try await KernelCryptography.initialise(
        withConfiguration: [
            (.defaultDatabaseID, DatabaseID.psql)
        ]
    )
    
    KernelFluentModel.Migrations.prepare(on: app, for: .psql)
    KernelCryptography.Fluent.Migrations.prepare(on: app, for: .psql)
    KernelX509.Fluent.Migrations.prepare(on: app, for: .psql)
    
    try app.register(
        collection: DocumentationController(
            title: "KSU Crypto X509 Demo",
            contentColor: .init(fromHex: "#45586e")
        )
    )
    
    try await app.autoMigrate()
}
