//
//  File.swift
//  
//
//  Created by Jonathan Forbes on 08/12/2023.
//

extension KernelLocalisation {
    public enum ISO639_1: String, Codable, CaseIterable, Sendable {
        case ab = "ab"          // Abkhazian
        case aa = "aa"          // Afar
        case af = "af"          // Afrikaans
        case ak = "ak"          // Akan
        case sq = "sq"          // Albanian
        case am = "am"          // Amharic
        case ar = "ar"          // Arabic
        case an = "an"          // Aragonese
        case hy = "hy"          // Armenian
        case `as` = "as"        // Assamese
        case av = "av"          // Avaric
        case ae = "ae"          // Avestan
        case ay = "ay"          // Aymara
        case az = "az"          // Azerbaijani
        case bm = "bm"          // Bambara
        case ba = "ba"          // Bashkir
        case eu = "eu"          // Basque
        case be = "be"          // Belarusian
        case bn = "bn"          // Bengali
        case bi = "bi"          // Bislama
        case bs = "bs"          // Bosnian
        case br = "br"          // Breton
        case bg = "bg"          // Bulgarian
        case my = "my"          // Burmese
        case ca = "ca"          // Catalan
        case ch = "ch"          // Chamorro
        case ce = "ce"          // Chechen
        case ny = "ny"          // Chichewa
        case zh = "zh"          // Chinese
        case cu = "cu"          // Church Slavonic
        case cv = "cv"          // Chuvash
        case kw = "kw"          // Cornish
        case co = "co"          // Corsican
        case cr = "cr"          // Cree
        case hr = "hr"          // Croatian
        case cs = "cs"          // Czech
        case da = "da"          // Danish
        case dv = "dv"          // Divehi
        case nl = "nl"          // Dutch
        case dz = "dz"          // Dzongkha
        case en = "en"          // English
        case eo = "eo"          // Esperanto
        case et = "et"          // Estonian
        case ee = "ee"          // Ewe
        case fo = "fo"          // Faroese
        case fj = "fj"          // Fijian
        case fi = "fi"          // Finnish
        case fr = "fr"          // French
        case fy = "fy"          // Western Frisian
        case ff = "ff"          // Fulah
        case gd = "gd"          // Gaelic
        case gl = "gl"          // Galician
        case lg = "lg"          // Ganda
        case ka = "ka"          // Georgian
        case de = "de"          // German
        case el = "el"          // Greek
        case kl = "kl"          // Kalaallisut
        case gn = "gn"          // Guarani
        case gu = "gu"          // Gujarati
        case ht = "ht"          // Haitian
        case ha = "ha"          // Hausa
        case he = "he"          // Hebrew
        case hz = "hz"          // Herero
        case hi = "hi"          // Hindi
        case ho = "ho"          // Hiri Motu
        case hu = "hu"          // Hungarian
        case `is` = "is"        // Icelandic
        case io = "io"          // Ido
        case ig = "ig"          // Igbo
        case id = "id"          // Indonesian
        case ia = "ia"          // Interlingua
        case ie = "ie"          // Interlingue
        case iu = "iu"          // Inuktitut
        case ik = "ik"          // Inupiaq
        case ga = "ga"          // Irish
        case it = "it"          // Italian
        case ja = "ja"          // Japanese
        case jv = "jv"          // Javanese
        case kn = "kn"          // Kannada
        case kr = "kr"          // Kanuri
        case ks = "ks"          // Kashmiri
        case kk = "kk"          // Kazakh
        case km = "km"          // Central Khmer
        case ki = "ki"          // Kikuyu
        case rw = "rw"          // Kinyarwanda
        case ky = "ky"          // Kirghiz
        case kv = "kv"          // Komi
        case kg = "kg"          // Kongo
        case ko = "ko"          // Korean
        case kj = "kj"          // Kuanyama
        case ku = "ku"          // Kurdish
        case lo = "lo"          // Lao
        case la = "la"          // Latin
        case lv = "lv"          // Latvian
        case li = "li"          // Limburgan
        case ln = "ln"          // Lingala
        case lt = "lt"          // Lithuanian
        case lu = "lu"          // Luba-Katanga
        case lb = "lb"          // Luxembourgish
        case mk = "mk"          // Macedonian
        case mg = "mg"          // Malagasy
        case ms = "ms"          // Malay
        case ml = "ml"          // Malayalam
        case mt = "mt"          // Maltese
        case gv = "gv"          // Manx
        case mi = "mi"          // Maori
        case mr = "mr"          // Marathi
        case mh = "mh"          // Marshallese
        case mn = "mn"          // Mongolian
        case na = "na"          // Nauru
        case nv = "nv"          // Navajo
        case nd = "nd"          // North Ndebele
        case nr = "nr"          // South Ndebele
        case ng = "ng"          // Ndonga
        case ne = "ne"          // Nepali
        case no = "no"          // Norwegian
        case nb = "nb"          // Norwegian Bokmål
        case nn = "nn"          // Norwegian Nynorsk
        case ii = "ii"          // Sichuan Yi
        case oc = "oc"          // Occitan
        case oj = "oj"          // Ojibwa
        case or = "or"          // Oriya
        case om = "om"          // Oromo
        case os = "os"          // Ossetian
        case pi = "pi"          // Pali
        case ps = "ps"          // Pashto
        case fa = "fa"          // Persian
        case pl = "pl"          // Polish
        case pt = "pt"          // Portuguese
        case pa = "pa"          // Punjabi
        case qu = "qu"          // Quechua
        case ro = "ro"          // Romanian
        case rm = "rm"          // Romansh
        case rn = "rn"          // Rundi
        case ru = "ru"          // Russian
        case se = "se"          // Northern Sami
        case sm = "sm"          // Samoan
        case sg = "sg"          // Sango
        case sa = "sa"          // Sanskrit
        case sc = "sc"          // Sardinian
        case sr = "sr"          // Serbian
        case sn = "sn"          // Shona
        case sd = "sd"          // Sindhi
        case si = "si"          // Sinhala
        case sk = "sk"          // Slovak
        case sl = "sl"          // Slovenian
        case so = "so"          // Somali
        case st = "st"          // Southern Sotho
        case es = "es"          // Spanish
        case su = "su"          // Sundanese
        case sw = "sw"          // Swahili
        case ss = "ss"          // Swati
        case sv = "sv"          // Swedish
        case tl = "tl"          // Tagalog
        case ty = "ty"          // Tahitian
        case tg = "tg"          // Tajik
        case ta = "ta"          // Tamil
        case tt = "tt"          // Tatar
        case te = "te"          // Telugu
        case th = "th"          // Thai
        case bo = "bo"          // Tibetan
        case ti = "ti"          // Tigrinya
        case to = "to"          // Tonga
        case ts = "ts"          // Tsonga
        case tn = "tn"          // Tswana
        case tr = "tr"          // Turkish
        case tk = "tk"          // Turkmen
        case tw = "tw"          // Twi
        case ug = "ug"          // Uighur
        case uk = "uk"          // Ukrainian
        case ur = "ur"          // Urdu
        case uz = "uz"          // Uzbek
        case ve = "ve"          // Venda
        case vi = "vi"          // Vietnamese
        case vo = "vo"          // Volapük
        case wa = "wa"          // Walloon
        case cy = "cy"          // Welsh
        case wo = "wo"          // Wolof
        case xh = "xh"          // Xhosa
        case yi = "yi"          // Yiddish
        case yo = "yo"          // Yoruba
        case za = "za"          // Zhuang
        case zu = "zu"          // Zulu
    }
}
