//
//  File.swift
//  
//
//  Created by Jonathan Forbes on 02/05/2023.
//

import Vapor

public enum ISO3166CountryPhoneCode: String, CaseIterable, Codable, Content, FluentStringEnum {
    public static let fluentEnumName: String = "ksc-iso_3166_c_phone_code"
    case US = "+1"
    case EG = "+20"
    case SS = "+211"
    case MA = "+212"
    case DZ = "+213"
    case TN = "+216"
    case LY = "+218"
    case GM = "+220"
    case SN = "+221"
    case MR = "+222"
    case ML = "+223"
    case GN = "+224"
    case CI = "+225"
    case BF = "+226"
    case NE = "+227"
    case TG = "+228"
    case BJ = "+229"
    case MU = "+230"
    case LR = "+231"
    case SL = "+232"
    case GH = "+233"
    case NG = "+234"
    case TD = "+235"
    case CF = "+236"
    case CM = "+237"
    case CV = "+238"
    case ST = "+239"
    case GQ = "+240"
    case GA = "+241"
    case CG = "+242"
    case CD = "+243"
    case AO = "+244"
    case GW = "+245"
    case DG = "+246"
    case SC = "+248"
    case SD = "+249"
    case RW = "+250"
    case ET = "+251"
    case SO = "+252"
    case DJ = "+253"
    case KE = "+254"
    case TZ = "+255"
    case UG = "+256"
    case BI = "+257"
    case MZ = "+258"
    case ZM = "+260"
    case MG = "+261"
    case RE = "+262"
    case ZW = "+263"
    case NA = "+264"
    case MW = "+265"
    case LS = "+266"
    case BW = "+267"
    case SZ = "+268"
    case KM = "+269"
    case ZA = "+27"
    case SH = "+290"
    case ER = "+291"
    case AW = "+297"
    case FO = "+298"
    case GL = "+299"
    case GR = "+30"
    case NL = "+31"
    case BE = "+32"
    case FR = "+33"
    case ES = "+34"
    case GI = "+350"
    case PT = "+351"
    case LU = "+352"
    case IE = "+353"
    case IS = "+354"
    case AL = "+355"
    case MT = "+356"
    case CY = "+357"
    case FI = "+358"
    case BG = "+359"
    case HU = "+36"
    case LT = "+370"
    case LV = "+371"
    case EE = "+372"
    case MD = "+373"
    case AM = "+374"
    case BY = "+375"
    case AD = "+376"
    case MC = "+377"
    case SM = "+378"
    case VA = "+379"
    case UA = "+380"
    case RS = "+381"
    case ME = "+382"
    case XK = "+383"
    case HR = "+385"
    case SI = "+386"
    case BA = "+387"
    case MK = "+389"
    case IT = "+39"
    case RO = "+40"
    case CH = "+41"
    case CZ = "+420"
    case SK = "+421"
    case LI = "+423"
    case AT = "+43"
    case GB = "+44"
    case DK = "+45"
    case SE = "+46"
    case NO = "+47"
    case PL = "+48"
    case DE = "+49"
    case FK = "+500"
    case BZ = "+501"
    case GT = "+502"
    case SV = "+503"
    case HN = "+504"
    case NI = "+505"
    case CR = "+506"
    case PA = "+507"
    case PM = "+508"
    case HT = "+509"
    case PE = "+51"
    case MX = "+52"
    case CU = "+53"
    case AR = "+54"
    case BR = "+55"
    case CL = "+56"
    case CO = "+57"
    case VE = "+58"
    case GP = "+590"
    case BO = "+591"
    case GY = "+592"
    case EC = "+593"
    case GF = "+594"
    case PY = "+595"
    case MQ = "+596"
    case SR = "+597"
    case UY = "+598"
    case CW = "+599"
    case MY = "+60"
    case AU = "+61"
    case ID = "+62"
    case PH = "+63"
    case NZ = "+64"
    case SG = "+65"
    case TH = "+66"
    case TL = "+670"
    case AQ = "+672"
    case BN = "+673"
    case NR = "+674"
    case PG = "+675"
    case TO = "+676"
    case SB = "+677"
    case VU = "+678"
    case FJ = "+679"
    case PW = "+680"
    case WF = "+681"
    case CK = "+682"
    case NU = "+683"
    case WS = "+685"
    case KI = "+686"
    case NC = "+687"
    case TV = "+688"
    case PF = "+689"
    case TK = "+690"
    case FM = "+691"
    case MH = "+692"
    case RU = "+7"
    case KZ = "+77"
    case JP = "+81"
    case KR = "+82"
    case VN = "+84"
    case KP = "+850"
    case HK = "+852"
    case MO = "+853"
    case KH = "+855"
    case LA = "+856"
    case CN = "+86"
    case BD = "+880"
    case TW = "+886"
    case TR = "+90"
    case IN = "+91"
    case PK = "+92"
    case AF = "+93"
    case LK = "+94"
    case MM = "+95"
    case MV = "+960"
    case LB = "+961"
    case JO = "+962"
    case SY = "+963"
    case IQ = "+964"
    case KW = "+965"
    case SA = "+966"
    case YE = "+967"
    case OM = "+968"
    case PS = "+970"
    case AE = "+971"
    case IL = "+972"
    case BH = "+973"
    case QA = "+974"
    case BT = "+975"
    case MN = "+976"
    case NP = "+977"
    case IR = "+98"
    case TJ = "+992"
    case TM = "+993"
    case AZ = "+994"
    case GE = "+995"
    case KG = "+996"
    case UZ = "+998"
    case unknown = ""
}

extension ISO3166CountryPhoneCode {
    public static func allValid() -> [ISO3166CountryPhoneCode] {
        return allCases.filter { $0 != .unknown }
    }
    
    public static func fromISO3166CountryAlpha2CodeStr(_ alpha2CodeStr: String) -> ISO3166CountryPhoneCode? {
        if let alpha2Code = ISO3166CountryAlpha2Code(rawValue: alpha2CodeStr.uppercased()) {
            return fromISO3166CountryAlpha2Code(alpha2Code)
        }
        else { return nil }
    }
    
    public static func fromISO3166CountryAlpha2Code(_ alpha2Code: ISO3166CountryAlpha2Code) -> ISO3166CountryPhoneCode? {
        switch alpha2Code {
        case .USA: return .US
        case .EGY: return .EG
        case .SSD: return .SS
        case .MAR: return .MA
        case .DZA: return .DZ
        case .TUN: return .TN
        case .LBY: return .LY
        case .GMB: return .GM
        case .SEN: return .SN
        case .MRT: return .MR
        case .MLI: return .ML
        case .GIN: return .GN
        case .CIV: return .CI
        case .BFA: return .BF
        case .NER: return .NE
        case .TGO: return .TG
        case .BEN: return .BJ
        case .MUS: return .MU
        case .LBR: return .LR
        case .SLE: return .SL
        case .GHA: return .GH
        case .NGA: return .NG
        case .TCD: return .TD
        case .CAF: return .CF
        case .CMR: return .CM
        case .CPV: return .CV
        case .STP: return .ST
        case .GNQ: return .GQ
        case .GAB: return .GA
        case .COG: return .CG
        case .COD: return .CD
        case .AGO: return .AO
        case .GNB: return .GW
        case .IOT: return .DG
        case .SYC: return .SC
        case .SDN: return .SD
        case .RWA: return .RW
        case .ETH: return .ET
        case .SOM: return .SO
        case .DJI: return .DJ
        case .KEN: return .KE
        case .TZA: return .TZ
        case .UGA: return .UG
        case .BDI: return .BI
        case .MOZ: return .MZ
        case .ZMB: return .ZM
        case .MDG: return .MG
        case .REU: return .RE
        case .ZWE: return .ZW
        case .NAM: return .NA
        case .MWI: return .MW
        case .LSO: return .LS
        case .BWA: return .BW
        case .SWZ: return .SZ
        case .COM: return .KM
        case .ZAF: return .ZA
        case .SHN: return .SH
        case .ERI: return .ER
        case .ABW: return .AW
        case .FRO: return .FO
        case .GRL: return .GL
        case .GRC: return .GR
        case .NLD: return .NL
        case .BEL: return .BE
        case .FRA: return .FR
        case .ESP: return .ES
        case .GIB: return .GI
        case .PRT: return .PT
        case .LUX: return .LU
        case .IRL: return .IE
        case .ISL: return .IS
        case .ALB: return .AL
        case .MLT: return .MT
        case .CYP: return .CY
        case .FIN: return .FI
        case .BGR: return .BG
        case .HUN: return .HU
        case .LTU: return .LT
        case .LVA: return .LV
        case .EST: return .EE
        case .MDA: return .MD
        case .ARM: return .AM
        case .BLR: return .BY
        case .AND: return .AD
        case .MCO: return .MC
        case .SMR: return .SM
        case .VAT: return .VA
        case .UKR: return .UA
        case .SRB: return .RS
        case .MNE: return .ME
//        case .NONE: return .XK
        case .HRV: return .HR
        case .SVN: return .SI
        case .BIH: return .BA
        case .MKD: return .MK
        case .ITA: return .IT
        case .ROU: return .RO
        case .CHE: return .CH
        case .CZE: return .CZ
        case .SVK: return .SK
        case .LIE: return .LI
        case .AUT: return .AT
        case .GBR: return .GB
        case .DNK: return .DK
        case .SWE: return .SE
        case .NOR: return .NO
        case .POL: return .PL
        case .DEU: return .DE
        case .FLK: return .FK
        case .BLZ: return .BZ
        case .GTM: return .GT
        case .SLV: return .SV
        case .HND: return .HN
        case .NIC: return .NI
        case .CRI: return .CR
        case .PAN: return .PA
        case .SPM: return .PM
        case .HTI: return .HT
        case .PER: return .PE
        case .MEX: return .MX
        case .CUB: return .CU
        case .ARG: return .AR
        case .BRA: return .BR
        case .CHL: return .CL
        case .COL: return .CO
        case .VEN: return .VE
        case .GLP: return .GP
        case .BOL: return .BO
        case .GUY: return .GY
        case .ECU: return .EC
        case .GUF: return .GF
        case .PRY: return .PY
        case .MTQ: return .MQ
        case .SUR: return .SR
        case .URY: return .UY
        case .CUW: return .CW
        case .MYS: return .MY
        case .AUS: return .AU
        case .IDN: return .ID
        case .PHL: return .PH
        case .NZL: return .NZ
        case .SGP: return .SG
        case .THA: return .TH
        case .TLS: return .TL
        case .ATA: return .AQ
        case .BRN: return .BN
        case .NRU: return .NR
        case .PNG: return .PG
        case .TON: return .TO
        case .SLB: return .SB
        case .VUT: return .VU
        case .FJI: return .FJ
        case .PLW: return .PW
        case .WLF: return .WF
        case .COK: return .CK
        case .NIU: return .NU
        case .WSM: return .WS
        case .KIR: return .KI
        case .NCL: return .NC
        case .TUV: return .TV
        case .PYF: return .PF
        case .TKL: return .TK
        case .FSM: return .FM
        case .MHL: return .MH
        case .RUS: return .RU
        case .KAZ: return .KZ
        case .JPN: return .JP
        case .KOR: return .KR
        case .VNM: return .VN
        case .PRK: return .KP
        case .HKG: return .HK
        case .MAC: return .MO
        case .KHM: return .KH
        case .LAO: return .LA
        case .CHN: return .CN
        case .BGD: return .BD
        case .TWN: return .TW
        case .TUR: return .TR
        case .IND: return .IN
        case .PAK: return .PK
        case .AFG: return .AF
        case .LKA: return .LK
        case .MMR: return .MM
        case .MDV: return .MV
        case .LBN: return .LB
        case .JOR: return .JO
        case .SYR: return .SY
        case .IRQ: return .IQ
        case .KWT: return .KW
        case .SAU: return .SA
        case .YEM: return .YE
        case .OMN: return .OM
        case .PSE: return .PS
        case .ARE: return .AE
        case .ISR: return .IL
        case .BHR: return .BH
        case .QAT: return .QA
        case .BTN: return .BT
        case .MNG: return .MN
        case .NPL: return .NP
        case .IRN: return .IR
        case .TJK: return .TJ
        case .TKM: return .TM
        case .AZE: return .AZ
        case .GEO: return .GE
        case .KGZ: return .KG
        case .UZB: return .UZ
        default: return nil
        }
    }
    
    public func toISO3166CountryAlpha2Code() -> ISO3166CountryAlpha2Code {
        switch self {
        case .US: return .USA
        case .EG: return .EGY
        case .SS: return .SSD
        case .MA: return .MAR
        case .DZ: return .DZA
        case .TN: return .TUN
        case .LY: return .LBY
        case .GM: return .GMB
        case .SN: return .SEN
        case .MR: return .MRT
        case .ML: return .MLI
        case .GN: return .GIN
        case .CI: return .CIV
        case .BF: return .BFA
        case .NE: return .NER
        case .TG: return .TGO
        case .BJ: return .BEN
        case .MU: return .MUS
        case .LR: return .LBR
        case .SL: return .SLE
        case .GH: return .GHA
        case .NG: return .NGA
        case .TD: return .TCD
        case .CF: return .CAF
        case .CM: return .CMR
        case .CV: return .CPV
        case .ST: return .STP
        case .GQ: return .GNQ
        case .GA: return .GAB
        case .CG: return .COG
        case .CD: return .COD
        case .AO: return .AGO
        case .GW: return .GNB
        case .DG: return .IOT
        case .SC: return .SYC
        case .SD: return .SDN
        case .RW: return .RWA
        case .ET: return .ETH
        case .SO: return .SOM
        case .DJ: return .DJI
        case .KE: return .KEN
        case .TZ: return .TZA
        case .UG: return .UGA
        case .BI: return .BDI
        case .MZ: return .MOZ
        case .ZM: return .ZMB
        case .MG: return .MDG
        case .RE: return .REU
        case .ZW: return .ZWE
        case .NA: return .NAM
        case .MW: return .MWI
        case .LS: return .LSO
        case .BW: return .BWA
        case .SZ: return .SWZ
        case .KM: return .COM
        case .ZA: return .ZAF
        case .SH: return .SHN
        case .ER: return .ERI
        case .AW: return .ABW
        case .FO: return .FRO
        case .GL: return .GRL
        case .GR: return .GRC
        case .NL: return .NLD
        case .BE: return .BEL
        case .FR: return .FRA
        case .ES: return .ESP
        case .GI: return .GIB
        case .PT: return .PRT
        case .LU: return .LUX
        case .IE: return .IRL
        case .IS: return .ISL
        case .AL: return .ALB
        case .MT: return .MLT
        case .CY: return .CYP
        case .FI: return .FIN
        case .BG: return .BGR
        case .HU: return .HUN
        case .LT: return .LTU
        case .LV: return .LVA
        case .EE: return .EST
        case .MD: return .MDA
        case .AM: return .ARM
        case .BY: return .BLR
        case .AD: return .AND
        case .MC: return .MCO
        case .SM: return .SMR
        case .VA: return .VAT
        case .UA: return .UKR
        case .RS: return .SRB
        case .ME: return .MNE
        case .XK: return .NONE
        case .HR: return .HRV
        case .SI: return .SVN
        case .BA: return .BIH
        case .MK: return .MKD
        case .IT: return .ITA
        case .RO: return .ROU
        case .CH: return .CHE
        case .CZ: return .CZE
        case .SK: return .SVK
        case .LI: return .LIE
        case .AT: return .AUT
        case .GB: return .GBR
        case .DK: return .DNK
        case .SE: return .SWE
        case .NO: return .NOR
        case .PL: return .POL
        case .DE: return .DEU
        case .FK: return .FLK
        case .BZ: return .BLZ
        case .GT: return .GTM
        case .SV: return .SLV
        case .HN: return .HND
        case .NI: return .NIC
        case .CR: return .CRI
        case .PA: return .PAN
        case .PM: return .SPM
        case .HT: return .HTI
        case .PE: return .PER
        case .MX: return .MEX
        case .CU: return .CUB
        case .AR: return .ARG
        case .BR: return .BRA
        case .CL: return .CHL
        case .CO: return .COL
        case .VE: return .VEN
        case .GP: return .GLP
        case .BO: return .BOL
        case .GY: return .GUY
        case .EC: return .ECU
        case .GF: return .GUF
        case .PY: return .PRY
        case .MQ: return .MTQ
        case .SR: return .SUR
        case .UY: return .URY
        case .CW: return .CUW
        case .MY: return .MYS
        case .AU: return .AUS
        case .ID: return .IDN
        case .PH: return .PHL
        case .NZ: return .NZL
        case .SG: return .SGP
        case .TH: return .THA
        case .TL: return .TLS
        case .AQ: return .ATA
        case .BN: return .BRN
        case .NR: return .NRU
        case .PG: return .PNG
        case .TO: return .TON
        case .SB: return .SLB
        case .VU: return .VUT
        case .FJ: return .FJI
        case .PW: return .PLW
        case .WF: return .WLF
        case .CK: return .COK
        case .NU: return .NIU
        case .WS: return .WSM
        case .KI: return .KIR
        case .NC: return .NCL
        case .TV: return .TUV
        case .PF: return .PYF
        case .TK: return .TKL
        case .FM: return .FSM
        case .MH: return .MHL
        case .RU: return .RUS
        case .KZ: return .KAZ
        case .JP: return .JPN
        case .KR: return .KOR
        case .VN: return .VNM
        case .KP: return .PRK
        case .HK: return .HKG
        case .MO: return .MAC
        case .KH: return .KHM
        case .LA: return .LAO
        case .CN: return .CHN
        case .BD: return .BGD
        case .TW: return .TWN
        case .TR: return .TUR
        case .IN: return .IND
        case .PK: return .PAK
        case .AF: return .AFG
        case .LK: return .LKA
        case .MM: return .MMR
        case .MV: return .MDV
        case .LB: return .LBN
        case .JO: return .JOR
        case .SY: return .SYR
        case .IQ: return .IRQ
        case .KW: return .KWT
        case .SA: return .SAU
        case .YE: return .YEM
        case .OM: return .OMN
        case .PS: return .PSE
        case .AE: return .ARE
        case .IL: return .ISR
        case .BH: return .BHR
        case .QA: return .QAT
        case .BT: return .BTN
        case .MN: return .MNG
        case .NP: return .NPL
        case .IR: return .IRN
        case .TJ: return .TJK
        case .TM: return .TKM
        case .AZ: return .AZE
        case .GE: return .GEO
        case .KG: return .KGZ
        case .UZ: return .UZB
        case .unknown: return .NONE
        }
    }
}
