//
//  File.swift
//  
//
//  Created by Jonathan Forbes on 08/09/2023.
//

extension KernelLocalisation.ISO639_1.CountrySpecific {
    public func descriptor(for descLanguage: KernelLocalisation.ISO639_1 = .en) -> String {
        switch self {
        case .ar_DZ     : "Arabic (Algeria)"
        case .ar_BH     : "Arabic (Bahrain)"
        case .ar_EG     : "Arabic (Egypt)"
        case .ar_IQ     : "Arabic (Iraq)"
        case .ar_JO     : "Arabic (Jordan)"
        case .ar_KW     : "Arabic (Kuwait)"
        case .ar_LB     : "Arabic (Lebanon)"
        case .ar_LY     : "Arabic (Libya)"
        case .ar_MA     : "Arabic (Morocco)"
        case .ar_OM     : "Arabic (Oman)"
        case .ar_QA     : "Arabic (Qatar)"
        case .ar_SA     : "Arabic (Saudi Arabia)"
        case .ar_SY     : "Arabic (Syria)"
        case .ar_TN     : "Arabic (Tunisia)"
        case .ar_AE     : "Arabic (U.A.E.)"
        case .ar_YE     : "Arabic (Yemen)"
        case .zh_HK     : "Chinese (Hong Kong)"
        case .zh_CN     : "Chinese (PRC)"
        case .zh_SG     : "Chinese (Singapore)"
        case .zh_TW     : "Chinese (Taiwan)"
        case .nl_BE     : "Dutch (Belgium)"
        case .nl_NL     : "Dutch (Netherlands)"
        case .en_AU     : "English (Australia)"
        case .en_BZ     : "English (Belize)"
        case .en_CA     : "English (Canada)"
        case .en_IE     : "English (Ireland)"
        case .en_JM     : "English (Jamaica)"
        case .en_NZ     : "English (New Zealand)"
        case .en_ZA     : "English (South Africa)"
        case .en_TT     : "English (Trinidad)"
        case .en_GB     : "English (United Kingdom)"
        case .en_US     : "English (United States)"
        case .fr_BE     : "French (Belgium)"
        case .fr_CA     : "French (Canada)"
        case .fr_FR     : "French (France)"
        case .fr_LU     : "French (Luxembourg)"
        case .fr_CH     : "French (Switzerland)"
        case .de_AT     : "German (Austria)"
        case .de_DE     : "German (Germany)"
        case .de_LI     : "German (Liechtenstein)"
        case .de_LU     : "German (Luxembourg)"
        case .de_CH     : "German (Switzerland)"
        case .it_IT     : "Italian (Italy)"
        case .it_CH     : "Italian (Switzerland)"
        case .pt_BR     : "Portuguese (Brazil)"
        case .pt_PT     : "Portuguese (Portugal)"
        case .ro_MD     : "Romanian (Republic of Moldova)"
        case .ro_RO     : "Romanian (Romania)"
        case .ru_MD     : "Russian (Republic of Moldova)"
        case .ru_RU     : "Russian (Russia)"
        case .es_AR     : "Spanish (Argentina)"
        case .es_BO     : "Spanish (Bolivia)"
        case .es_CL     : "Spanish (Chile)"
        case .es_CO     : "Spanish (Colombia)"
        case .es_CR     : "Spanish (Costa Rica)"
        case .es_DO     : "Spanish (Dominican Republic)"
        case .es_EC     : "Spanish (Ecuador)"
        case .es_SV     : "Spanish (El Salvador)"
        case .es_GT     : "Spanish (Guatemala)"
        case .es_HN     : "Spanish (Honduras)"
        case .es_MX     : "Spanish (Mexico)"
        case .es_NI     : "Spanish (Nicaragua)"
        case .es_ES     : "Spanish (Spain)"
        case .es_PA     : "Spanish (Panama)"
        case .es_PY     : "Spanish (Paraguay)"
        case .es_PE     : "Spanish (Peru)"
        case .es_PR     : "Spanish (Puerto Rico)"
        case .es_UY     : "Spanish (Uruguay)"
        case .es_VE     : "Spanish (Venezuela)"
        case .sv_FI     : "Swedish (Finland)"
        case .sv_SE     : "Swedish (Sweden)"
        }
    }
}
