//
//  File.swift
//
//
//  Created by Jonathan Forbes on 08/09/2023.
//

extension KernelLocalisation.ISO639_1 {
    public func description(for descLanguage: Self = .en) -> String {
        switch self {
        case .ab    : "Abkhazian"
        case .aa    : "Afar"
        case .af    : "Afrikaans"
        case .ak    : "Akan"
        case .sq    : "Albanian"
        case .am    : "Amharic"
        case .ar    : "Arabic"
        case .an    : "Aragonese"
        case .hy    : "Armenian"
        case .as    : "Assamese"
        case .av    : "Avaric"
        case .ae    : "Avestan"
        case .ay    : "Aymara"
        case .az    : "Azerbaijani"
        case .bm    : "Bambara"
        case .ba    : "Bashkir"
        case .eu    : "Basque"
        case .be    : "Belarusian"
        case .bn    : "Bengali"
        case .bi    : "Bislama"
        case .bs    : "Bosnian"
        case .br    : "Breton"
        case .bg    : "Bulgarian"
        case .my    : "Burmese"
        case .ca    : "Catalan"
        case .ch    : "Chamorro"
        case .ce    : "Chechen"
        case .ny    : "Chichewa"
        case .zh    : "Chinese"
        case .cu    : "Church Slavonic"
        case .cv    : "Chuvash"
        case .kw    : "Cornish"
        case .co    : "Corsican"
        case .cr    : "Cree"
        case .hr    : "Croatian"
        case .cs    : "Czech"
        case .da    : "Danish"
        case .dv    : "Divehi"
        case .nl    : "Dutch"
        case .dz    : "Dzongkha"
        case .en    : "English"
        case .eo    : "Esperanto"
        case .et    : "Estonian"
        case .ee    : "Ewe"
        case .fo    : "Faroese"
        case .fj    : "Fijian"
        case .fi    : "Finnish"
        case .fr    : "French"
        case .fy    : "Western Frisian"
        case .ff    : "Fulah"
        case .gd    : "Gaelic"
        case .gl    : "Galician"
        case .lg    : "Ganda"
        case .ka    : "Georgian"
        case .de    : "German"
        case .el    : "Greek"
        case .kl    : "Kalaallisut"
        case .gn    : "Guarani"
        case .gu    : "Gujarati"
        case .ht    : "Haitian"
        case .ha    : "Hausa"
        case .he    : "Hebrew"
        case .hz    : "Herero"
        case .hi    : "Hindi"
        case .ho    : "Hiri Motu"
        case .hu    : "Hungarian"
        case .is    : "Icelandic"
        case .io    : "Ido"
        case .ig    : "Igbo"
        case .id    : "Indonesian"
        case .ia    : "Interlingua"
        case .ie    : "Interlingue"
        case .iu    : "Inuktitut"
        case .ik    : "Inupiaq"
        case .ga    : "Irish"
        case .it    : "Italian"
        case .ja    : "Japanese"
        case .jv    : "Javanese"
        case .kn    : "Kannada"
        case .kr    : "Kanuri"
        case .ks    : "Kashmiri"
        case .kk    : "Kazakh"
        case .km    : "Central Khmer"
        case .ki    : "Kikuyu"
        case .rw    : "Kinyarwanda"
        case .ky    : "Kirghiz"
        case .kv    : "Komi"
        case .kg    : "Kongo"
        case .ko    : "Korean"
        case .kj    : "Kuanyama"
        case .ku    : "Kurdish"
        case .lo    : "Lao"
        case .la    : "Latin"
        case .lv    : "Latvian"
        case .li    : "Limburgan"
        case .ln    : "Lingala"
        case .lt    : "Lithuanian"
        case .lu    : "Luba-Katanga"
        case .lb    : "Luxembourgish"
        case .mk    : "Macedonian"
        case .mg    : "Malagasy"
        case .ms    : "Malay"
        case .ml    : "Malayalam"
        case .mt    : "Maltese"
        case .gv    : "Manx"
        case .mi    : "Maori"
        case .mr    : "Marathi"
        case .mh    : "Marshallese"
        case .mn    : "Mongolian"
        case .na    : "Nauru"
        case .nv    : "Navajo"
        case .nd    : "North Ndebele"
        case .nr    : "South Ndebele"
        case .ng    : "Ndonga"
        case .ne    : "Nepali"
        case .no    : "Norwegian"
        case .nb    : "Norwegian Bokmål"
        case .nn    : "Norwegian Nynorsk"
        case .ii    : "Sichuan Yi"
        case .oc    : "Occitan"
        case .oj    : "Ojibwa"
        case .or    : "Oriya"
        case .om    : "Oromo"
        case .os    : "Ossetian"
        case .pi    : "Pali"
        case .ps    : "Pashto"
        case .fa    : "Persian"
        case .pl    : "Polish"
        case .pt    : "Portuguese"
        case .pa    : "Punjabi"
        case .qu    : "Quechua"
        case .ro    : "Romanian"
        case .rm    : "Romansh"
        case .rn    : "Rundi"
        case .ru    : "Russian"
        case .se    : "Northern Sami"
        case .sm    : "Samoan"
        case .sg    : "Sango"
        case .sa    : "Sanskrit"
        case .sc    : "Sardinian"
        case .sr    : "Serbian"
        case .sn    : "Shona"
        case .sd    : "Sindhi"
        case .si    : "Sinhala"
        case .sk    : "Slovak"
        case .sl    : "Slovenian"
        case .so    : "Somali"
        case .st    : "Southern Sotho"
        case .es    : "Spanish"
        case .su    : "Sundanese"
        case .sw    : "Swahili"
        case .ss    : "Swati"
        case .sv    : "Swedish"
        case .tl    : "Tagalog"
        case .ty    : "Tahitian"
        case .tg    : "Tajik"
        case .ta    : "Tamil"
        case .tt    : "Tatar"
        case .te    : "Telugu"
        case .th    : "Thai"
        case .bo    : "Tibetan"
        case .ti    : "Tigrinya"
        case .to    : "Tonga"
        case .ts    : "Tsonga"
        case .tn    : "Tswana"
        case .tr    : "Turkish"
        case .tk    : "Turkmen"
        case .tw    : "Twi"
        case .ug    : "Uighur"
        case .uk    : "Ukrainian"
        case .ur    : "Urdu"
        case .uz    : "Uzbek"
        case .ve    : "Venda"
        case .vi    : "Vietnamese"
        case .vo    : "Volapük"
        case .wa    : "Walloon"
        case .cy    : "Welsh"
        case .wo    : "Wolof"
        case .xh    : "Xhosa"
        case .yi    : "Yiddish"
        case .yo    : "Yoruba"
        case .za    : "Zhuang"
        case .zu    : "Zulu"
        }
    }
}
