//
//  File.swift
//  
//
//  Created by Jonathan Forbes on 08/12/2023.
//

extension KernelLocalisation.ISO3166 {
    public enum Alpha2: String, Codable, CaseIterable, Sendable {
        case af = "af"          // Afghanistan
        case ax = "ax"          // Aland Islands
        case al = "al"          // Albania
        case dz = "dz"          // Algeria
        case `as` = "as"        // American Samoa
        case ad = "ad"          // Andorra
        case ao = "ao"          // Angola
        case ai = "ai"          // Anguilla
        case aq = "aq"          // Antarctica
        case ag = "ag"          // Antigua and Barbuda
        case ar = "ar"          // Argentina
        case am = "am"          // Armenia
        case aw = "aw"          // Aruba
        case au = "au"          // Australia
        case at = "at"          // Austria
        case az = "az"          // Azerbaijan
        case bs = "bs"          // Bahamas
        case bh = "bh"          // Bahrain
        case bd = "bd"          // Bangladesh
        case bb = "bb"          // Barbados
        case by = "by"          // Belarus
        case be = "be"          // Belgium
        case bz = "bz"          // Belize
        case bj = "bj"          // Benin
        case bm = "bm"          // Bermuda
        case bt = "bt"          // Bhutan
        case bo = "bo"          // Bolivia
        case bq = "bq"          // Bonaire, Saint Eustatius and Saba
        case ba = "ba"          // Bosnia and Herzegovina
        case bw = "bw"          // Botswana
        case bv = "bv"          // Bouvet Island
        case br = "br"          // Brazil
        case io = "io"          // British Indian Ocean Territory
        case vg = "vg"          // British Virgin Islands
        case bn = "bn"          // Brunei
        case bg = "bg"          // Bulgaria
        case bf = "bf"          // Burkina Faso
        case bi = "bi"          // Burundi
        case kh = "kh"          // Cambodia
        case cm = "cm"          // Cameroon
        case ca = "ca"          // Canada
        case cv = "cv"          // Cape Verde
        case ky = "ky"          // Cayman Islands
        case cf = "cf"          // Central African Republic
        case td = "td"          // Chad
        case cl = "cl"          // Chile
        case cn = "cn"          // China
        case cx = "cx"          // Christmas Island
        case cc = "cc"          // Cocos Islands
        case co = "co"          // Colombia
        case km = "km"          // Comoros
        case ck = "ck"          // Cook Islands
        case cr = "cr"          // Costa Rica
        case hr = "hr"          // Croatia
        case cu = "cu"          // Cuba
        case cw = "cw"          // Curacao
        case cy = "cy"          // Cyprus
        case cz = "cz"          // Czech Republic
        case cd = "cd"          // Democratic Republic of the Congo
        case dk = "dk"          // Denmark
        case dj = "dj"          // Djibouti
        case dm = "dm"          // Dominica
        case `do` = "do"        // Dominican Republic
        case tl = "tl"          // East Timor
        case ec = "ec"          // Ecuador
        case eg = "eg"          // Egypt
        case sv = "sv"          // El Salvador
        case gq = "gq"          // Equatorial Guinea
        case er = "er"          // Eritrea
        case ee = "ee"          // Estonia
        case et = "et"          // Ethiopia
        case fk = "fk"          // Falkland Islands
        case fo = "fo"          // Faroe Islands
        case fj = "fj"          // Fiji
        case fi = "fi"          // Finland
        case fr = "fr"          // France
        case gf = "gf"          // French Guiana
        case pf = "pf"          // French Polynesia
        case tf = "tf"          // French Southern Territories
        case ga = "ga"          // Gabon
        case gm = "gm"          // Gambia
        case ge = "ge"          // Georgia
        case de = "de"          // Germany
        case gh = "gh"          // Ghana
        case gi = "gi"          // Gibraltar
        case gr = "gr"          // Greece
        case gl = "gl"          // Greenland
        case gd = "gd"          // Grenada
        case gp = "gp"          // Guadeloupe
        case gu = "gu"          // Guam
        case gt = "gt"          // Guatemala
        case gg = "gg"          // Guernsey
        case gn = "gn"          // Guinea
        case gw = "gw"          // Guinea-Bissau
        case gy = "gy"          // Guyana
        case ht = "ht"          // Haiti
        case hm = "hm"          // Heard Island and McDonald Islands
        case hn = "hn"          // Honduras
        case hk = "hk"          // Hong Kong
        case hu = "hu"          // Hungary
        case `is` = "is"        // Iceland
        case `in` = "in"        // India
        case id = "id"          // Indonesia
        case ir = "ir"          // Iran
        case iq = "iq"          // Iraq
        case ie = "ie"          // Ireland
        case im = "im"          // Isle of Man
        case il = "il"          // Israel
        case it = "it"          // Italy
        case ci = "ci"          // Ivory Coast
        case jm = "jm"          // Jamaica
        case jp = "jp"          // Japan
        case je = "je"          // Jersey
        case jo = "jo"          // Jordan
        case kz = "kz"          // Kazakhstan
        case ke = "ke"          // Kenya
        case ki = "ki"          // Kiribati
        case kw = "kw"          // Kuwait
        case kg = "kg"          // Kyrgyzstan
        case la = "la"          // Laos
        case lv = "lv"          // Latvia
        case lb = "lb"          // Lebanon
        case ls = "ls"          // Lesotho
        case lr = "lr"          // Liberia
        case ly = "ly"          // Libya
        case li = "li"          // Liechtenstein
        case lt = "lt"          // Lithuania
        case lu = "lu"          // Luxembourg
        case mo = "mo"          // Macao
        case mk = "mk"          // Macedonia
        case mg = "mg"          // Madagascar
        case mw = "mw"          // Malawi
        case my = "my"          // Malaysia
        case mv = "mv"          // Maldives
        case ml = "ml"          // Mali
        case mt = "mt"          // Malta
        case mh = "mh"          // Marshall Islands
        case mq = "mq"          // Martinique
        case mr = "mr"          // Mauritania
        case mu = "mu"          // Mauritius
        case yt = "yt"          // Mayotte
        case mx = "mx"          // Mexico
        case fm = "fm"          // Micronesia
        case md = "md"          // Moldova
        case mc = "mc"          // Monaco
        case mn = "mn"          // Mongolia
        case me = "me"          // Montenegro
        case ms = "ms"          // Montserrat
        case ma = "ma"          // Morocco
        case mz = "mz"          // Mozambique
        case mm = "mm"          // Myanmar
        case na = "na"          // Namibia
        case nr = "nr"          // Nauru
        case np = "np"          // Nepal
        case nl = "nl"          // Netherlands
        case nc = "nc"          // New Caledonia
        case nz = "nz"          // New Zealand
        case ni = "ni"          // Nicaragua
        case ne = "ne"          // Niger
        case ng = "ng"          // Nigeria
        case nu = "nu"          // Niue
        case nf = "nf"          // Norfolk Island
        case kp = "kp"          // North Korea
        case mp = "mp"          // Northern Mariana Islands
        case no = "no"          // Norway
        case om = "om"          // Oman
        case pk = "pk"          // Pakistan
        case pw = "pw"          // Palau
        case ps = "ps"          // Palestinian Territory
        case pa = "pa"          // Panama
        case pg = "pg"          // Papua New Guinea
        case py = "py"          // Paraguay
        case pe = "pe"          // Peru
        case ph = "ph"          // Philippines
        case pn = "pn"          // Pitcairn
        case pl = "pl"          // Poland
        case pt = "pt"          // Portugal
        case pr = "pr"          // Puerto Rico
        case qa = "qa"          // Qatar
        case cg = "cg"          // Republic of the Congo
        case re = "re"          // Reunion
        case ro = "ro"          // Romania
        case ru = "ru"          // Russia
        case rw = "rw"          // Rwanda
        case bl = "bl"          // Saint Barthelemy
        case sh = "sh"          // Saint Helena
        case kn = "kn"          // Saint Kitts and Nevis
        case lc = "lc"          // Saint Lucia
        case mf = "mf"          // Saint Martin
        case pm = "pm"          // Saint Pierre and Miquelon
        case vc = "vc"          // Saint Vincent and the Grenadines
        case ws = "ws"          // Samoa
        case sm = "sm"          // San Marino
        case st = "st"          // Sao Tome and Principe
        case sa = "sa"          // Saudi Arabia
        case sn = "sn"          // Senegal
        case rs = "rs"          // Serbia
        case sc = "sc"          // Seychelles
        case sl = "sl"          // Sierra Leone
        case sg = "sg"          // Singapore
        case sx = "sx"          // Sint Maarten
        case sk = "sk"          // Slovakia
        case si = "si"          // Slovenia
        case sb = "sb"          // Solomon Islands
        case so = "so"          // Somalia
        case za = "za"          // South Africa
        case gs = "gs"          // South Georgia and the South Sandwich Islands
        case kr = "kr"          // South Korea
        case ss = "ss"          // South Sudan
        case es = "es"          // Spain
        case lk = "lk"          // Sri Lanka
        case sd = "sd"          // Sudan
        case sr = "sr"          // Suriname
        case sj = "sj"          // Svalbard and Jan Mayen
        case sz = "sz"          // Swaziland
        case se = "se"          // Sweden
        case ch = "ch"          // Switzerland
        case sy = "sy"          // Syria
        case tw = "tw"          // Taiwan
        case tj = "tj"          // Tajikistan
        case tz = "tz"          // Tanzania
        case th = "th"          // Thailand
        case tg = "tg"          // Togo
        case tk = "tk"          // Tokelau
        case to = "to"          // Tonga
        case tt = "tt"          // Trinidad and Tobago
        case tn = "tn"          // Tunisia
        case tr = "tr"          // Turkey
        case tm = "tm"          // Turkmenistan
        case tc = "tc"          // Turks and Caicos Islands
        case tv = "tv"          // Tuvalu
        case vi = "vi"          // U.S. Virgin Islands
        case ug = "ug"          // Uganda
        case ua = "ua"          // Ukraine
        case ae = "ae"          // United Arab Emirates
        case gb = "gb"          // United Kingdom
        case us = "us"          // United States
        case um = "um"          // United States Minor Outlying Islands
        case uy = "uy"          // Uruguay
        case uz = "uz"          // Uzbekistan
        case vu = "vu"          // Vanuatu
        case va = "va"          // Vatican
        case ve = "ve"          // Venezuela
        case vn = "vn"          // Vietnam
        case wf = "wf"          // Wallis and Futuna
        case eh = "eh"          // Western Sahara
        case ye = "ye"          // Yemen
        case zm = "zm"          // Zambia
        case zw = "zw"          // Zimbabwe
    }
}
