//
//  File.swift
//  
//
//  Created by Jonathan Forbes on 08/12/2023.
//

extension KernelLocalisation.ISO3166.Alpha2 {
    public func descriptor(for descLanguage: KernelLocalisation.ISO639_1 = .en) -> String {
        switch self {
        case .af    : "Afghanistan"
        case .ax    : "Aland Islands"
        case .al    : "Albania"
        case .dz    : "Algeria"
        case .as    : "American Samoa"
        case .ad    : "Andorra"
        case .ao    : "Angola"
        case .ai    : "Anguilla"
        case .aq    : "Antarctica"
        case .ag    : "Antigua and Barbuda"
        case .ar    : "Argentina"
        case .am    : "Armenia"
        case .aw    : "Aruba"
        case .au    : "Australia"
        case .at    : "Austria"
        case .az    : "Azerbaijan"
        case .bs    : "Bahamas"
        case .bh    : "Bahrain"
        case .bd    : "Bangladesh"
        case .bb    : "Barbados"
        case .by    : "Belarus"
        case .be    : "Belgium"
        case .bz    : "Belize"
        case .bj    : "Benin"
        case .bm    : "Bermuda"
        case .bt    : "Bhutan"
        case .bo    : "Bolivia"
        case .bq    : "Bonaire, Saint Eustatius and Saba"
        case .ba    : "Bosnia and Herzegovina"
        case .bw    : "Botswana"
        case .bv    : "Bouvet Island"
        case .br    : "Brazil"
        case .io    : "British Indian Ocean Territory"
        case .vg    : "British Virgin Islands"
        case .bn    : "Brunei"
        case .bg    : "Bulgaria"
        case .bf    : "Burkina Faso"
        case .bi    : "Burundi"
        case .kh    : "Cambodia"
        case .cm    : "Cameroon"
        case .ca    : "Canada"
        case .cv    : "Cape Verde"
        case .ky    : "Cayman Islands"
        case .cf    : "Central African Republic"
        case .td    : "Chad"
        case .cl    : "Chile"
        case .cn    : "China"
        case .cx    : "Christmas Island"
        case .cc    : "Cocos Islands"
        case .co    : "Colombia"
        case .km    : "Comoros"
        case .ck    : "Cook Islands"
        case .cr    : "Costa Rica"
        case .hr    : "Croatia"
        case .cu    : "Cuba"
        case .cw    : "Curacao"
        case .cy    : "Cyprus"
        case .cz    : "Czech Republic"
        case .cd    : "Democratic Republic of the Congo"
        case .dk    : "Denmark"
        case .dj    : "Djibouti"
        case .dm    : "Dominica"
        case .do    : "Dominican Republic"
        case .tl    : "East Timor"
        case .ec    : "Ecuador"
        case .eg    : "Egypt"
        case .sv    : "El Salvador"
        case .gq    : "Equatorial Guinea"
        case .er    : "Eritrea"
        case .ee    : "Estonia"
        case .et    : "Ethiopia"
        case .fk    : "Falkland Islands"
        case .fo    : "Faroe Islands"
        case .fj    : "Fiji"
        case .fi    : "Finland"
        case .fr    : "France"
        case .gf    : "French Guiana"
        case .pf    : "French Polynesia"
        case .tf    : "French Southern Territories"
        case .ga    : "Gabon"
        case .gm    : "Gambia"
        case .ge    : "Georgia"
        case .de    : "Germany"
        case .gh    : "Ghana"
        case .gi    : "Gibraltar"
        case .gr    : "Greece"
        case .gl    : "Greenland"
        case .gd    : "Grenada"
        case .gp    : "Guadeloupe"
        case .gu    : "Guam"
        case .gt    : "Guatemala"
        case .gg    : "Guernsey"
        case .gn    : "Guinea"
        case .gw    : "Guinea-Bissau"
        case .gy    : "Guyana"
        case .ht    : "Haiti"
        case .hm    : "Heard Island and McDonald Islands"
        case .hn    : "Honduras"
        case .hk    : "Hong Kong"
        case .hu    : "Hungary"
        case .is    : "Iceland"
        case .in    : "India"
        case .id    : "Indonesia"
        case .ir    : "Iran"
        case .iq    : "Iraq"
        case .ie    : "Ireland"
        case .im    : "Isle of Man"
        case .il    : "Israel"
        case .it    : "Italy"
        case .ci    : "Ivory Coast"
        case .jm    : "Jamaica"
        case .jp    : "Japan"
        case .je    : "Jersey"
        case .jo    : "Jordan"
        case .kz    : "Kazakhstan"
        case .ke    : "Kenya"
        case .ki    : "Kiribati"
        case .kw    : "Kuwait"
        case .kg    : "Kyrgyzstan"
        case .la    : "Laos"
        case .lv    : "Latvia"
        case .lb    : "Lebanon"
        case .ls    : "Lesotho"
        case .lr    : "Liberia"
        case .ly    : "Libya"
        case .li    : "Liechtenstein"
        case .lt    : "Lithuania"
        case .lu    : "Luxembourg"
        case .mo    : "Macao"
        case .mk    : "Macedonia"
        case .mg    : "Madagascar"
        case .mw    : "Malawi"
        case .my    : "Malaysia"
        case .mv    : "Maldives"
        case .ml    : "Mali"
        case .mt    : "Malta"
        case .mh    : "Marshall Islands"
        case .mq    : "Martinique"
        case .mr    : "Mauritania"
        case .mu    : "Mauritius"
        case .yt    : "Mayotte"
        case .mx    : "Mexico"
        case .fm    : "Micronesia"
        case .md    : "Moldova"
        case .mc    : "Monaco"
        case .mn    : "Mongolia"
        case .me    : "Montenegro"
        case .ms    : "Montserrat"
        case .ma    : "Morocco"
        case .mz    : "Mozambique"
        case .mm    : "Myanmar"
        case .na    : "Namibia"
        case .nr    : "Nauru"
        case .np    : "Nepal"
        case .nl    : "Netherlands"
        case .nc    : "New Caledonia"
        case .nz    : "New Zealand"
        case .ni    : "Nicaragua"
        case .ne    : "Niger"
        case .ng    : "Nigeria"
        case .nu    : "Niue"
        case .nf    : "Norfolk Island"
        case .kp    : "North Korea"
        case .mp    : "Northern Mariana Islands"
        case .no    : "Norway"
        case .om    : "Oman"
        case .pk    : "Pakistan"
        case .pw    : "Palau"
        case .ps    : "Palestinian Territory"
        case .pa    : "Panama"
        case .pg    : "Papua New Guinea"
        case .py    : "Paraguay"
        case .pe    : "Peru"
        case .ph    : "Philippines"
        case .pn    : "Pitcairn"
        case .pl    : "Poland"
        case .pt    : "Portugal"
        case .pr    : "Puerto Rico"
        case .qa    : "Qatar"
        case .cg    : "Republic of the Congo"
        case .re    : "Reunion"
        case .ro    : "Romania"
        case .ru    : "Russia"
        case .rw    : "Rwanda"
        case .bl    : "Saint Barthelemy"
        case .sh    : "Saint Helena"
        case .kn    : "Saint Kitts and Nevis"
        case .lc    : "Saint Lucia"
        case .mf    : "Saint Martin"
        case .pm    : "Saint Pierre and Miquelon"
        case .vc    : "Saint Vincent and the Grenadines"
        case .ws    : "Samoa"
        case .sm    : "San Marino"
        case .st    : "Sao Tome and Principe"
        case .sa    : "Saudi Arabia"
        case .sn    : "Senegal"
        case .rs    : "Serbia"
        case .sc    : "Seychelles"
        case .sl    : "Sierra Leone"
        case .sg    : "Singapore"
        case .sx    : "Sint Maarten"
        case .sk    : "Slovakia"
        case .si    : "Slovenia"
        case .sb    : "Solomon Islands"
        case .so    : "Somalia"
        case .za    : "South Africa"
        case .gs    : "South Georgia and the South Sandwich Islands"
        case .kr    : "South Korea"
        case .ss    : "South Sudan"
        case .es    : "Spain"
        case .lk    : "Sri Lanka"
        case .sd    : "Sudan"
        case .sr    : "Suriname"
        case .sj    : "Svalbard and Jan Mayen"
        case .sz    : "Swaziland"
        case .se    : "Sweden"
        case .ch    : "Switzerland"
        case .sy    : "Syria"
        case .tw    : "Taiwan"
        case .tj    : "Tajikistan"
        case .tz    : "Tanzania"
        case .th    : "Thailand"
        case .tg    : "Togo"
        case .tk    : "Tokelau"
        case .to    : "Tonga"
        case .tt    : "Trinidad and Tobago"
        case .tn    : "Tunisia"
        case .tr    : "Turkey"
        case .tm    : "Turkmenistan"
        case .tc    : "Turks and Caicos Islands"
        case .tv    : "Tuvalu"
        case .vi    : "U.S. Virgin Islands"
        case .ug    : "Uganda"
        case .ua    : "Ukraine"
        case .ae    : "United Arab Emirates"
        case .gb    : "United Kingdom"
        case .us    : "United States"
        case .um    : "United States Minor Outlying Islands"
        case .uy    : "Uruguay"
        case .uz    : "Uzbekistan"
        case .vu    : "Vanuatu"
        case .va    : "Vatican"
        case .ve    : "Venezuela"
        case .vn    : "Vietnam"
        case .wf    : "Wallis and Futuna"
        case .eh    : "Western Sahara"
        case .ye    : "Yemen"
        case .zm    : "Zambia"
        case .zw    : "Zimbabwe"
        }
    }
}
